language: node_js
os: osx

git: 
  depth: 3

branches:
  except:
    - legacy
    - experimental

branches:
  only:
    - master

before_install:
  - python

  install:
    - yarn install

script:
  - yarn deploy
  - yarn test

before_script:
  - yarn test

after_script:
  - yarn clean

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
    script: yarn test
    script: yarn eslint
    - stage: deploy
    script: yarn deploy


deploy:
  provider: heroku
  on
    repo: pacool84/travis-ci